[doc [title Basic PDML Specification]

    [table
        [tr [tc [b Version]][tc 1.0.1]]
        [tr [tc [b Published]][tc 2021-12-03]]
        [tr [tc [b License]][tc [link url=https://creativecommons.org/licenses/by-nd/4.0// text="CC BY-ND 4.0"]]]
        [tr [tc [b Website]][tc [link url=https://pdml-lang.dev/ text="https://pdml-lang.dev/"]]]
        [tr [tc [b Author]][tc Christian Neumanns]]
    ]

    [u:set pdml_website_url=https://pdml-lang.dev/]
    [u:set pdml_docs_url=[u:get pdml_website_url]docs/]

    [u:ins_file path=01_introduction.pml]
    [u:ins_file path=02_document_structure.pml]
    [u:ins_file path=03_escape_rules.pml]
    [u:ins_file path=04_whitespace.pml]
    [u:ins_file path=05_new_lines.pml]
    [u:ins_file path=06_encoding.pml]
    [u:ins_file path=07_grammar.pml]
    [u:ins_file path=08_examples.pml]
    [u:ins_file path=09_license.pml]
    [u:ins_file path=10_versioning.pml]
    [u:ins_file path=11_website.pml]
    [u:ins_file path=12_source_code.pml]
]
